# Generated by Django 2.2.6 on 2019-10-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=120)),
                ('titlePart1', models.CharField(max_length=120)),
                ('textPart1', models.TextField(null=True)),
                ('titlePart2', models.CharField(max_length=120)),
                ('textPart2', models.TextField(null=True)),
            ],
        ),
    ]
