# Generated by Django 2.2.6 on 2019-10-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainContent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='MainContent',
        ),
    ]
