# Generated by Django 2.2.6 on 2019-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=models.CharField(max_length=120)),
        ),
    ]
