# Generated by Django 2.2.6 on 2019-11-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191104_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
