# Generated by Django 2.2.6 on 2019-11-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendemail',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='lastName',
        ),
        migrations.AddField(
            model_name='sendemail',
            name='subject',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
