# Generated by Django 2.2.6 on 2019-10-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmentalProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalproject',
            name='description',
        ),
        migrations.AddField(
            model_name='environmentalproject',
            name='fullDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='environmentalproject',
            name='intro',
            field=models.TextField(null=True),
        ),
    ]
