# Generated by Django 2.2.6 on 2019-10-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmentalProject', '0002_auto_20191014_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalproject',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
