# Generated by Django 2.2.6 on 2019-10-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='icon',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
