# Generated by Django 2.2.6 on 2019-11-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('streetAddress', models.CharField(max_length=120)),
                ('zipCode', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('buyerId', models.IntegerField(blank=True)),
                ('username', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
