# Generated by Django 2.2.6 on 2019-11-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='id',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyerId',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
