# Generated by Django 2.2.6 on 2019-11-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20191105_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='username',
            new_name='sellerName',
        ),
    ]
